USE [AVR_CASHE]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[AVR_HumanCaseReportCustom_65K]') AND type in (N'U'))
DROP TABLE [dbo].[AVR_HumanCaseReportCustom_65K]
GO



CREATE TABLE [dbo].[AVR_HumanCaseReportCustom_65K](
	[sflHC_ExposureDate] [datetime] NULL, 
	[sflHC_PatientAgeGroup] [nvarchar](200) NULL, 
	[sflHC_CurrentLocation] [nvarchar](400) NULL, 
	[sflHC_PatientAgeType_ID] [bigint] NULL, 
	[sflHC_PatientAgeType] [nvarchar](4000) NULL, 
	[sflHC_PatientPhone] [nvarchar](400) NULL, 
	[sflHC_FacilityLastVisitDate] [datetime] NULL, 
	[sflHC_PatientName] [nvarchar](1204) NULL, 
	[sflHC_PatientOccupation_ID] [bigint] NULL, 
	[sflHC_PatientOccupation] [nvarchar](4000) NULL, 
	[sflHC_PatientDeathDate] [datetime] NULL, 
	[sflHC_PatientNationality_ID] [bigint] NULL, 
	[sflHC_PatientNationality] [nvarchar](4000) NULL, 
	[sflHC_PatientFirstSoughtCareDate] [datetime] NULL, 
	[sflHC_HospitalizationPlace] [nvarchar](400) NULL, 
	[sflHC_PatientHospitalizationDate] [datetime] NULL, 
	[sflHC_HospitalizationStatus_ID] [bigint] NULL, 
	[sflHC_HospitalizationStatus] [nvarchar](4000) NULL, 
	[sflHC_PatientSex_ID] [bigint] NULL, 
	[sflHC_PatientSex] [nvarchar](4000) NULL, 
	[sflHC_CaseClassification_ID] [bigint] NULL, 
	[sflHC_CaseClassification] [nvarchar](4000) NULL, 
	[sflHC_SamplesCollected_ID] [bigint] NULL, 
	[sflHC_SamplesCollected] [nvarchar](4000) NULL, 
	[sflHC_InvestigationStartDate] [datetime] NULL, 
	[sflHC_InvestigatedByOffice_ID] [bigint] NULL, 
	[sflHC_InvestigatedByOffice] [nvarchar](4000) NULL, 
	[sflHC_NotificationDate] [datetime] NULL, 
	[sflHC_LocalID] [nvarchar](400) NULL, 
	[sflHC_ReceivedByOffice_ID] [bigint] NULL, 
	[sflHC_ReceivedByOffice] [nvarchar](4000) NULL, 
	[sflHC_SentByOffice_ID] [bigint] NULL, 
	[sflHC_SentByOffice] [nvarchar](4000) NULL, 
	[sflHC_PatientNotificationStatus_ID] [bigint] NULL, 
	[sflHC_PatientNotificationStatus] [nvarchar](4000) NULL, 
	[sflHC_ModificationDate] [datetime] NULL, 
	[sflHC_SymptomOnsetDate] [datetime] NULL, 
	[sflHC_ReceivedByPerson] [nvarchar](1204) NULL, 
	[sflHC_SentByPerson] [nvarchar](1204) NULL, 
	[sflHC_PatientAge] [int] NULL, 
	[sflHC_CompletionPaperFormDate] [datetime] NULL, 
	[sflHC_PatientEmployerPhone] [nvarchar](400) NULL, 
	[sflHC_PatientEmployer] [nvarchar](400) NULL, 
	[sflHC_PatientEmpAddress] [nvarchar](1606) NULL, 
	[sflHC_PatientEmpRegion_ID] [bigint] NULL, 
	[sflHC_PatientEmpRegion] [nvarchar](730) NULL, 
	[sflHC_PatientEmpRayon_ID] [bigint] NULL, 
	[sflHC_PatientEmpRayon] [nvarchar](730) NULL, 
	[sflHC_PatientEmpSettlement_ID] [bigint] NULL, 
	[sflHC_PatientEmpSettlement] [nvarchar](730) NULL, 
	[sflHC_FinalCaseClassification_ID] [bigint] NULL, 
	[sflHC_FinalCaseClassification] [nvarchar](4000) NULL, 
	[sflHC_AntimicrobialTherapy_ID] [bigint] NULL, 
	[sflHC_AntimicrobialTherapy] [nvarchar](4000) NULL, 
	[sflHC_Outcome_ID] [bigint] NULL, 
	[sflHC_Outcome] [nvarchar](4000) NULL, 
	[sflHC_CaseProgressStatus_ID] [bigint] NULL, 
	[sflHC_CaseProgressStatus] [nvarchar](4000) NULL, 
	[sflHC_FinalDiagnosisCode] [nvarchar](400) NULL, 
	[sflHC_FinalDiagnosisDate] [datetime] NULL, 
	[sflHC_FinalDiagnosis_ID] [bigint] NULL, 
	[sflHC_FinalDiagnosis] [nvarchar](4000) NULL, 
	[sflHC_InitialCaseClassification_ID] [bigint] NULL, 
	[sflHC_InitialCaseClassification] [nvarchar](4000) NULL, 
	[sflHC_Hospitalization_ID] [bigint] NULL, 
	[sflHC_Hospitalization] [nvarchar](4000) NULL, 
	[sflHC_PatientCRAddress] [nvarchar](1606) NULL, 
	[sflHC_PatientCRRegion_ID] [bigint] NULL, 
	[sflHC_PatientCRRegion] [nvarchar](730) NULL, 
	[sflHC_PatientCRRayon_ID] [bigint] NULL, 
	[sflHC_PatientCRRayon] [nvarchar](730) NULL, 
	[sflHC_PatientCRSettlement_ID] [bigint] NULL, 
	[sflHC_PatientCRSettlement] [nvarchar](730) NULL, 
	[sflHC_CaseID] [nvarchar](400) NULL, 
	[sflHC_RelatedToOutbreak_ID] [bigint] NULL, 
	[sflHC_RelatedToOutbreak] [nvarchar](4000) NULL, 
	[sflHC_LocationSettlement_ID] [bigint] NULL, 
	[sflHC_LocationSettlement] [nvarchar](730) NULL, 
	[sflHC_LocationRegion_ID] [bigint] NULL, 
	[sflHC_LocationRegion] [nvarchar](730) NULL, 
	[sflHC_LocationRayon_ID] [bigint] NULL, 
	[sflHC_LocationRayon] [nvarchar](730) NULL, 
	[sflHC_LocationCoordinates] [nvarchar](128) NULL, 
	[sflHC_PatientDOB] [datetime] NULL, 
	[sflHC_DiagnosisDate] [datetime] NULL, 
	[sflHC_DiagnosisCode] [nvarchar](400) NULL, 
	[sflHC_LabDiagBasis_ID] [int] NULL, 
	[sflHC_LabDiagBasis] [nvarchar](4000) NULL, 
	[sflHC_ClinicalDiagBasis_ID] [int] NULL, 
	[sflHC_ClinicalDiagBasis] [nvarchar](4000) NULL, 
	[sflHC_EpiDiagBasis_ID] [int] NULL, 
	[sflHC_EpiDiagBasis] [nvarchar](4000) NULL, 
	[sflHC_ChangedDiagnosisDate] [datetime] NULL, 
	[sflHC_Diagnosis_ID] [bigint] NULL, 
	[sflHC_Diagnosis] [nvarchar](4000) NULL, 
	[sflHC_ChangedDiagnosisCode] [nvarchar](400) NULL, 
	[sflHC_ChangedDiagnosis_ID] [bigint] NULL, 
	[sflHC_ChangedDiagnosis] [nvarchar](4000) NULL, 
	[sflHC_EnteredDate] [datetime] NULL, 
	[sflHC_PatientDischargeDate] [datetime] NULL, 
	[sflHC_DaysAfterNotification] [int] NULL, 
	[sflHC_OutbreakID] [nvarchar](400) NULL
) ON [PRIMARY]

GO

INSERT into [dbo].[AVR_HumanCaseReportCustom_65K]
select 
	sflHC_ExposureDate,
	sflHC_PatientAgeGroup,
	sflHC_CurrentLocation,
	sflHC_PatientAgeType_ID,
	sflHC_PatientAgeType,
	sflHC_PatientPhone,
	sflHC_FacilityLastVisitDate,
	sflHC_PatientName,
	sflHC_PatientOccupation_ID,
	sflHC_PatientOccupation,
	sflHC_PatientDeathDate,
	sflHC_PatientNationality_ID,
	sflHC_PatientNationality,
	sflHC_PatientFirstSoughtCareDate,
	sflHC_HospitalizationPlace,
	sflHC_PatientHospitalizationDate,
	sflHC_HospitalizationStatus_ID,
	sflHC_HospitalizationStatus,
	sflHC_PatientSex_ID,
	sflHC_PatientSex,
	sflHC_CaseClassification_ID,
	sflHC_CaseClassification,
	sflHC_SamplesCollected_ID,
	sflHC_SamplesCollected,
	sflHC_InvestigationStartDate,
	sflHC_InvestigatedByOffice_ID,
	sflHC_InvestigatedByOffice,
	sflHC_NotificationDate,
	sflHC_LocalID,
	sflHC_ReceivedByOffice_ID,
	sflHC_ReceivedByOffice,
	sflHC_SentByOffice_ID,
	sflHC_SentByOffice,
	sflHC_PatientNotificationStatus_ID,
	sflHC_PatientNotificationStatus,
	sflHC_ModificationDate,
	sflHC_SymptomOnsetDate,
	sflHC_ReceivedByPerson,
	sflHC_SentByPerson,
	sflHC_PatientAge,
	sflHC_CompletionPaperFormDate,
	sflHC_PatientEmployerPhone,
	sflHC_PatientEmployer,
	sflHC_PatientEmpAddress,
	sflHC_PatientEmpRegion_ID,
	sflHC_PatientEmpRegion,
	sflHC_PatientEmpRayon_ID,
	sflHC_PatientEmpRayon,
	sflHC_PatientEmpSettlement_ID,
	sflHC_PatientEmpSettlement,
	sflHC_FinalCaseClassification_ID,
	sflHC_FinalCaseClassification,
	sflHC_AntimicrobialTherapy_ID,
	sflHC_AntimicrobialTherapy,
	sflHC_Outcome_ID,
	sflHC_Outcome,
	sflHC_CaseProgressStatus_ID,
	sflHC_CaseProgressStatus,
	sflHC_FinalDiagnosisCode,
	sflHC_FinalDiagnosisDate,
	sflHC_FinalDiagnosis_ID,
	sflHC_FinalDiagnosis,
	sflHC_InitialCaseClassification_ID,
	sflHC_InitialCaseClassification,
	sflHC_Hospitalization_ID,
	sflHC_Hospitalization,
	sflHC_PatientCRAddress,
	sflHC_PatientCRRegion_ID,
	sflHC_PatientCRRegion,
	sflHC_PatientCRRayon_ID,
	sflHC_PatientCRRayon,
	sflHC_PatientCRSettlement_ID,
	sflHC_PatientCRSettlement,
	sflHC_CaseID,
	sflHC_RelatedToOutbreak_ID,
	sflHC_RelatedToOutbreak,
	sflHC_LocationSettlement_ID,
	sflHC_LocationSettlement,
	sflHC_LocationRegion_ID,
	sflHC_LocationRegion,
	sflHC_LocationRayon_ID,
	sflHC_LocationRayon,
	sflHC_LocationCoordinates,
	sflHC_PatientDOB,
	sflHC_DiagnosisDate,
	sflHC_DiagnosisCode,
	sflHC_LabDiagBasis_ID,
	sflHC_LabDiagBasis,
	sflHC_ClinicalDiagBasis_ID,
	sflHC_ClinicalDiagBasis,
	sflHC_EpiDiagBasis_ID,
	sflHC_EpiDiagBasis,
	sflHC_ChangedDiagnosisDate,
	sflHC_Diagnosis_ID,
	sflHC_Diagnosis,
	sflHC_ChangedDiagnosisCode,
	sflHC_ChangedDiagnosis_ID,
	sflHC_ChangedDiagnosis,
	sflHC_EnteredDate,
	sflHC_PatientDischargeDate,
	sflHC_DaysAfterNotification,
	sflHC_OutbreakID
from [EIDSS_v5_AZ_65k].[dbo].fnM0BSearchQuery__8957000086489570000864('en')

--select * from [dbo].[AVR_HumanCaseReportCustom_65K]

