USE [AVR_CASHE]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[AVR_HumanCasesWithSamplesAndTestsReport_65K]') AND type in (N'U'))
DROP TABLE [dbo].[AVR_HumanCasesWithSamplesAndTestsReportGG_65K]
GO



CREATE TABLE [dbo].[AVR_HumanCasesWithSamplesAndTestsReportGG_65K](
	[sflHC_CaseID] [nvarchar](400) NULL, 
	[sflHC_Diagnosis_ID] [bigint] NULL, 
	[sflHC_Diagnosis] [nvarchar](4000) NULL, 
	[sflHC_DiagnosisDate] [datetime] NULL, 
	[sflHC_ChangedDiagnosis_ID] [bigint] NULL, 
	[sflHC_ChangedDiagnosis] [nvarchar](4000) NULL, 
	[sflHC_ChangedDiagnosisDate] [datetime] NULL, 
	[sflHC_FinalDiagnosis_ID] [bigint] NULL, 
	[sflHC_FinalDiagnosis] [nvarchar](4000) NULL, 
	[sflHC_FinalDiagnosisDate] [datetime] NULL, 
	[sflHC_EnteredDate] [datetime] NULL, 
	[sflHC_NotificationDate] [datetime] NULL, 
	[sflHC_PatientAge] [int] NULL, 
	[sflHC_PatientAgeType_ID] [bigint] NULL, 
	[sflHC_PatientAgeType] [nvarchar](4000) NULL, 
	[sflHC_PatientDOB] [datetime] NULL, 
	[sflHC_PatientCRRayon_ID] [bigint] NULL, 
	[sflHC_PatientCRRayon] [nvarchar](730) NULL, 
	[sflHC_PatientCRRegion_ID] [bigint] NULL, 
	[sflHC_PatientCRRegion] [nvarchar](730) NULL, 
	[sflHC_PatientCRSettlement_ID] [bigint] NULL, 
	[sflHC_PatientCRSettlement] [nvarchar](730) NULL, 
	[sflHC_PatientName] [nvarchar](1204) NULL, 
	[sflHC_PatientSex_ID] [bigint] NULL, 
	[sflHC_PatientSex] [nvarchar](4000) NULL, 
	[sflHC_PatientAgeGroup] [nvarchar](200) NULL, 
	[sflHC_CompletionPaperFormDate] [datetime] NULL, 
	[sflHC_SymptomOnsetDate] [datetime] NULL, 
	[sflHC_CaseClassification_ID] [bigint] NULL, 
	[sflHC_CaseClassification] [nvarchar](4000) NULL, 
	[sflHC_CaseProgressStatus_ID] [bigint] NULL, 
	[sflHC_CaseProgressStatus] [nvarchar](4000) NULL, 
	[sflHC_SamplesCollected_ID] [bigint] NULL, 
	[sflHC_SamplesCollected] [nvarchar](4000) NULL, 
	[sflHCSample_AccessionDate] [datetime] NULL, 
	[sflHCSample_CollectionDate] [datetime] NULL, 
	[sflHCSample_AccessionCondition_ID] [bigint] NULL, 
	[sflHCSample_AccessionCondition] [nvarchar](4000) NULL, 
	[sflHCSample_SampleType_ID] [bigint] NULL, 
	[sflHCSample_SampleType] [nvarchar](4000) NULL, 
	[sflHCSample_LabSampleID] [nvarchar](400) NULL, 
	[sflHCTest_TestType_ID] [bigint] NULL, 
	[sflHCTest_TestType] [nvarchar](4000) NULL, 
	[sflHCTest_Diagnosis_ID] [bigint] NULL, 
	[sflHCTest_Diagnosis] [nvarchar](4000) NULL, 
	[sflHCTest_TestResult_ID] [bigint] NULL, 
	[sflHCTest_TestResult] [nvarchar](4000) NULL, 
	[sflHCTest_TestStatus_ID] [bigint] NULL, 
	[sflHCTest_TestStatus] [nvarchar](4000) NULL, 
	[sflHCTest_PerformedDate] [datetime] NULL
) ON [PRIMARY]

GO

INSERT into [dbo].[AVR_HumanCasesWithSamplesAndTestsReportGG_65K]
select 
	sflHC_CaseID,
	sflHC_Diagnosis_ID,
	sflHC_Diagnosis,
	sflHC_DiagnosisDate,
	sflHC_ChangedDiagnosis_ID,
	sflHC_ChangedDiagnosis,
	sflHC_ChangedDiagnosisDate,
	sflHC_FinalDiagnosis_ID,
	sflHC_FinalDiagnosis,
	sflHC_FinalDiagnosisDate,
	sflHC_EnteredDate,
	sflHC_NotificationDate,
	sflHC_PatientAge,
	sflHC_PatientAgeType_ID,
	sflHC_PatientAgeType,
	sflHC_PatientDOB,
	sflHC_PatientCRRayon_ID,
	sflHC_PatientCRRayon,
	sflHC_PatientCRRegion_ID,
	sflHC_PatientCRRegion,
	sflHC_PatientCRSettlement_ID,
	sflHC_PatientCRSettlement,
	sflHC_PatientName,
	sflHC_PatientSex_ID,
	sflHC_PatientSex,
	sflHC_PatientAgeGroup,
	sflHC_CompletionPaperFormDate,
	sflHC_SymptomOnsetDate,
	sflHC_CaseClassification_ID,
	sflHC_CaseClassification,
	sflHC_CaseProgressStatus_ID,
	sflHC_CaseProgressStatus,
	sflHC_SamplesCollected_ID,
	sflHC_SamplesCollected,
	sflHCSample_AccessionDate,
	sflHCSample_CollectionDate,
	sflHCSample_AccessionCondition_ID,
	sflHCSample_AccessionCondition,
	sflHCSample_SampleType_ID,
	sflHCSample_SampleType,
	sflHCSample_LabSampleID,
	sflHCTest_TestType_ID,
	sflHCTest_TestType,
	sflHCTest_Diagnosis_ID,
	sflHCTest_Diagnosis,
	sflHCTest_TestResult_ID,
	sflHCTest_TestResult,
	sflHCTest_TestStatus_ID,
	sflHCTest_TestStatus,
	sflHCTest_PerformedDate
from [EIDSS_v5_GG_65k].[dbo].fn_AVR_HumanCasesWithSamplesAndTestsReport('en')

--select * from [dbo].[[AVR_HumanCasesWithSamplesAndTestsReportGG_65K]]

