//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eidss.mobileclient.MobileReportService
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "MobileReportService.IReportFacade")]
    public interface IReportFacade
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumAggregateCase", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumAggregateCaseResponse")]
        byte[] ExportHumAggregateCase(eidss.model.Reports.Common.AggregateModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumAggregateCaseSummary", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumAggregateCaseSummaryResponse")]
        byte[] ExportHumAggregateCaseSummary(eidss.model.Reports.Common.AggregateSummaryModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumCaseInvestigation", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumCaseInvestigationResponse")]
        byte[] ExportHumCaseInvestigation(eidss.model.Reports.Common.HumIdModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumUrgentyNotification", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumUrgentyNotificationResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.HumIdModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.AggregateActionsModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.VetIdModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimTestResultModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimTestModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimBatchTestModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.AggregateModel))]
        byte[] ExportHumUrgentyNotification(eidss.model.Reports.Common.BaseIdModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumDiagnosisToChangedDiagnosis", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumDiagnosisToChangedDiagnosisResponse")]
        byte[] ExportHumDiagnosisToChangedDiagnosis(eidss.model.Reports.Common.DToChangedDSurrogateModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumMonthlyMorbidityAndMortality", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumMonthlyMorbidityAndMortalityResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.ARM.FormN85SurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.DToChangedDSurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.VersionedDateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.GG.MonthInfectiousDiseaseModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.DataQualityIndicatorsSurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.WhoMeaslesRubellaModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.BorderRayonsSurrogateModel))]
        byte[] ExportHumMonthlyMorbidityAndMortality(eidss.model.Reports.Common.BaseDateModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHum60BJournal", ReplyAction = "http://tempuri.org/IReportFacade/ExportHum60BJournalResponse")]
        byte[] ExportHum60BJournal(eidss.model.Reports.GG.Hum60BJournalModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumMonthInfectiousDiseaseV4", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumMonthInfectiousDiseaseV4Response")]
        byte[] ExportHumMonthInfectiousDiseaseV4(eidss.model.Reports.GG.MonthInfectiousDiseaseModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumMonthInfectiousDiseaseV5", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumMonthInfectiousDiseaseV5Response")]
        byte[] ExportHumMonthInfectiousDiseaseV5(eidss.model.Reports.GG.MonthInfectiousDiseaseModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumMonthInfectiousDiseaseV6", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumMonthInfectiousDiseaseV6Response")]
        byte[] ExportHumMonthInfectiousDiseaseV6(eidss.model.Reports.GG.MonthInfectiousDiseaseModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumMonthInfectiousDiseaseV61", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumMonthInfectiousDiseaseV61Response")]
        byte[] ExportHumMonthInfectiousDiseaseV61(eidss.model.Reports.GG.MonthInfectiousDiseaseModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumIntermediateMonthInfectiousDiseaseV4", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumIntermediateMonthInfectiousDiseaseV4Res" +
            "ponse")]
        byte[] ExportHumIntermediateMonthInfectiousDiseaseV4(eidss.model.Reports.GG.IntermediateInfectiousDiseaseSurrogateModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumIntermediateMonthInfectiousDiseaseV5", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumIntermediateMonthInfectiousDiseaseV5Res" +
            "ponse")]
        byte[] ExportHumIntermediateMonthInfectiousDiseaseV5(eidss.model.Reports.GG.IntermediateInfectiousDiseaseSurrogateModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumIntermediateMonthInfectiousDiseaseV6", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumIntermediateMonthInfectiousDiseaseV6Res" +
            "ponse")]
        byte[] ExportHumIntermediateMonthInfectiousDiseaseV6(eidss.model.Reports.GG.IntermediateInfectiousDiseaseSurrogateModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumIntermediateMonthInfectiousDiseaseV61", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumIntermediateMonthInfectiousDiseaseV61Re" +
            "sponse")]
        byte[] ExportHumIntermediateMonthInfectiousDiseaseV61(eidss.model.Reports.GG.IntermediateInfectiousDiseaseSurrogateModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumAnnualInfectiousDisease", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumAnnualInfectiousDiseaseResponse")]
        byte[] ExportHumAnnualInfectiousDisease(eidss.model.Reports.GG.AnnualInfectiousDiseaseModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumIntermediateAnnualInfectiousDisease", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumIntermediateAnnualInfectiousDiseaseResp" +
            "onse")]
        byte[] ExportHumIntermediateAnnualInfectiousDisease(eidss.model.Reports.GG.IntermediateInfectiousDiseaseSurrogateModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumSerologyResearchCard", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumSerologyResearchCardResponse")]
        byte[] ExportHumSerologyResearchCard(eidss.model.Reports.GG.HumanLabSampleModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumMicrobiologyResearchCard", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumMicrobiologyResearchCardResponse")]
        byte[] ExportHumMicrobiologyResearchCard(eidss.model.Reports.GG.HumanLabSampleModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumAntibioticResistanceCard", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumAntibioticResistanceCardResponse")]
        byte[] ExportHumAntibioticResistanceCard(eidss.model.Reports.GG.HumanLabSampleModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumAntibioticResistanceCardLma", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumAntibioticResistanceCardLmaResponse")]
        byte[] ExportHumAntibioticResistanceCardLma(eidss.model.Reports.Common.VetLabSampleModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportVetRabiesBulletinEurope", ReplyAction = "http://tempuri.org/IReportFacade/ExportVetRabiesBulletinEuropeResponse")]
        byte[] ExportVetRabiesBulletinEurope(eidss.model.Reports.GG.RBESurrogateModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportVetLaboratoryResearchResult", ReplyAction = "http://tempuri.org/IReportFacade/ExportVetLaboratoryResearchResultResponse")]
        byte[] ExportVetLaboratoryResearchResult(eidss.model.Reports.GG.VetLaboratoryResearchResultModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumFormN1", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumFormN1Response")]
        byte[] ExportHumFormN1(eidss.model.Reports.AZ.FormNo1SurrogateModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumDataQualityIndicators", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumDataQualityIndicatorsResponse")]
        byte[] ExportHumDataQualityIndicators(eidss.model.Reports.AZ.DataQualityIndicatorsSurrogateModel surrogateModel);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumDataQualityIndicatorsRayons", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumDataQualityIndicatorsRayonsResponse")]
        byte[] ExportHumDataQualityIndicatorsRayons(eidss.model.Reports.AZ.DataQualityIndicatorsSurrogateModel surrogateModel);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumSummaryByRayonDiagnosisAgeGroups", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumSummaryByRayonDiagnosisAgeGroupsRespons" +
            "e")]
        byte[] ExportHumSummaryByRayonDiagnosisAgeGroups(eidss.model.Reports.AZ.SummaryByRayonDiagnosisModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumComparativeAZReport", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumComparativeAZReportResponse")]
        byte[] ExportHumComparativeAZReport(eidss.model.Reports.AZ.ComparativeSurrogateModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumExternalComparativeReport", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumExternalComparativeReportResponse")]
        byte[] ExportHumExternalComparativeReport(eidss.model.Reports.AZ.ExternalComparativeSurrogateModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumMainIndicatorsOfAFPSurveillance", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumMainIndicatorsOfAFPSurveillanceResponse" +
            "")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.VetLabSurrogateModel))]
        byte[] ExportHumMainIndicatorsOfAFPSurveillance(eidss.model.Reports.AZ.AFPModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumAdditionalIndicatorsOfAFPSurveillance", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumAdditionalIndicatorsOfAFPSurveillanceRe" +
            "sponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.VetLabSurrogateModel))]
        byte[] ExportHumAdditionalIndicatorsOfAFPSurveillance(eidss.model.Reports.AZ.AFPModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumWhoMeaslesRubellaReport", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumWhoMeaslesRubellaReportResponse")]
        byte[] ExportHumWhoMeaslesRubellaReport(eidss.model.Reports.AZ.WhoMeaslesRubellaModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumComparativeReportOfTwoYears", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumComparativeReportOfTwoYearsResponse")]
        byte[] ExportHumComparativeReportOfTwoYears(eidss.model.Reports.AZ.ComparativeTwoYearsSurrogateModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumBorderRayonsComparativeReport", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumBorderRayonsComparativeReportResponse")]
        byte[] ExportHumBorderRayonsComparativeReport(eidss.model.Reports.AZ.BorderRayonsSurrogateModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumTuberculosisCasesTested", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumTuberculosisCasesTestedResponse")]
        byte[] ExportHumTuberculosisCasesTested(eidss.model.Reports.AZ.TuberculosisSurrogateModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportLabTestingResultsAZ", ReplyAction = "http://tempuri.org/IReportFacade/ExportLabTestingResultsAZResponse")]
        byte[] ExportLabTestingResultsAZ(eidss.model.Reports.AZ.LabTestingTesultsModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportAssignmentLabDiagnosticAZ", ReplyAction = "http://tempuri.org/IReportFacade/ExportAssignmentLabDiagnosticAZResponse")]
        byte[] ExportAssignmentLabDiagnosticAZ(eidss.model.Reports.AZ.AssignmentLabDiagnosticModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportZoonoticComparativeAZ", ReplyAction = "http://tempuri.org/IReportFacade/ExportZoonoticComparativeAZResponse")]
        byte[] ExportZoonoticComparativeAZ(eidss.model.Reports.AZ.ZoonoticSurrogateModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumComparativeIQReport", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumComparativeIQReportResponse")]
        byte[] ExportHumComparativeIQReport(eidss.model.Reports.AZ.ComparativeSurrogateModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportWeeklySituationDiseasesByAgeGroupAndSex", ReplyAction = "http://tempuri.org/IReportFacade/ExportWeeklySituationDiseasesByAgeGroupAndSexRes" +
            "ponse")]
        byte[] ExportWeeklySituationDiseasesByAgeGroupAndSex(eidss.model.Reports.IQ.SituationOnInfectiousDiseasesSurrogateModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportMonthlySituationDiseasesByAgeGroupAndSex", ReplyAction = "http://tempuri.org/IReportFacade/ExportMonthlySituationDiseasesByAgeGroupAndSexRe" +
            "sponse")]
        byte[] ExportMonthlySituationDiseasesByAgeGroupAndSex(eidss.model.Reports.IQ.SituationOnInfectiousDiseasesSurrogateModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportWeeklySituationDiseasesByDistricts", ReplyAction = "http://tempuri.org/IReportFacade/ExportWeeklySituationDiseasesByDistrictsResponse" +
            "")]
        byte[] ExportWeeklySituationDiseasesByDistricts(eidss.model.Reports.IQ.SituationOnInfectiousDiseasesSurrogateModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportMonthlySituationDiseasesByDistricts", ReplyAction = "http://tempuri.org/IReportFacade/ExportMonthlySituationDiseasesByDistrictsRespons" +
            "e")]
        byte[] ExportMonthlySituationDiseasesByDistricts(eidss.model.Reports.IQ.SituationOnInfectiousDiseasesSurrogateModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportVeterinaryCasesReport", ReplyAction = "http://tempuri.org/IReportFacade/ExportVeterinaryCasesReportResponse")]
        byte[] ExportVeterinaryCasesReport(eidss.model.Reports.AZ.VetCasesSurrogateModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportVeterinaryLaboratoriesAZReport", ReplyAction = "http://tempuri.org/IReportFacade/ExportVeterinaryLaboratoriesAZReportResponse")]
        byte[] ExportVeterinaryLaboratoriesAZReport(eidss.model.Reports.AZ.VetLabSurrogateModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportVeterinaryFormVet1", ReplyAction = "http://tempuri.org/IReportFacade/ExportVeterinaryFormVet1Response")]
        byte[] ExportVeterinaryFormVet1(eidss.model.Reports.AZ.VetCasesSurrogateModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportVeterinaryFormVet1A", ReplyAction = "http://tempuri.org/IReportFacade/ExportVeterinaryFormVet1AResponse")]
        byte[] ExportVeterinaryFormVet1A(eidss.model.Reports.AZ.VetCasesSurrogateModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportVeterinarySummaryAZ", ReplyAction = "http://tempuri.org/IReportFacade/ExportVeterinarySummaryAZResponse")]
        byte[] ExportVeterinarySummaryAZ(eidss.model.Reports.AZ.VetSummaryModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumComparativeReportOfSeveralYearsTH", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumComparativeReportOfSeveralYearsTHRespon" +
            "se")]
        byte[] ExportHumComparativeReportOfSeveralYearsTH(eidss.model.Reports.TH.ComparativeSeveralYearsTHSurrogateModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumNumberOfCasesDeathsMorbidityMortalityTH" +
            "", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumNumberOfCasesDeathsMorbidityMortalityTH" +
            "Response")]
        byte[] ExportHumNumberOfCasesDeathsMorbidityMortalityTH(eidss.model.Reports.TH.NumberOfCasesDeathsMorbidityMortalityTHModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumNumberOfCasesDeathsMonthTH", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumNumberOfCasesDeathsMonthTHResponse")]
        byte[] ExportHumNumberOfCasesDeathsMonthTH(eidss.model.Reports.TH.NumberOfCasesDeathsMonthTHModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportHumFormN85ARM", ReplyAction = "http://tempuri.org/IReportFacade/ExportHumFormN85ARMResponse")]
        byte[] ExportHumFormN85ARM(eidss.model.Reports.ARM.FormN85SurrogateModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportVetAggregateCase", ReplyAction = "http://tempuri.org/IReportFacade/ExportVetAggregateCaseResponse")]
        byte[] ExportVetAggregateCase(eidss.model.Reports.Common.AggregateModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportVetAggregateCaseSummary", ReplyAction = "http://tempuri.org/IReportFacade/ExportVetAggregateCaseSummaryResponse")]
        byte[] ExportVetAggregateCaseSummary(eidss.model.Reports.Common.AggregateSummaryModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportVetAggregateCaseActions", ReplyAction = "http://tempuri.org/IReportFacade/ExportVetAggregateCaseActionsResponse")]
        byte[] ExportVetAggregateCaseActions(eidss.model.Reports.Common.AggregateActionsModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportVetAggregateCaseActionsSummary", ReplyAction = "http://tempuri.org/IReportFacade/ExportVetAggregateCaseActionsSummaryResponse")]
        byte[] ExportVetAggregateCaseActionsSummary(eidss.model.Reports.Common.AggregateActionsSummaryModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportVetAvianInvestigation", ReplyAction = "http://tempuri.org/IReportFacade/ExportVetAvianInvestigationResponse")]
        byte[] ExportVetAvianInvestigation(eidss.model.Reports.Common.VetIdModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportVetLivestockInvestigation", ReplyAction = "http://tempuri.org/IReportFacade/ExportVetLivestockInvestigationResponse")]
        byte[] ExportVetLivestockInvestigation(eidss.model.Reports.Common.VetIdModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportVetActiveSurveillanceSampleCollected", ReplyAction = "http://tempuri.org/IReportFacade/ExportVetActiveSurveillanceSampleCollectedRespon" +
            "se")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.HumIdModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.AggregateActionsModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.VetIdModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimTestResultModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimTestModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimBatchTestModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.AggregateModel))]
        byte[] ExportVetActiveSurveillanceSampleCollected(eidss.model.Reports.Common.BaseIdModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportVetSamplesCount", ReplyAction = "http://tempuri.org/IReportFacade/ExportVetSamplesCountResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.KZ.InfectiousParasiticKZSurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.TH.BaseThaiYearModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.TH.NumberOfCasesDeathsMonthTHModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.GG.AnnualInfectiousDiseaseModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.BaseYearQuarterModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.GG.RBESurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.FormNo1SurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.AFPModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.VetLabSurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.ZoonoticSurrogateModel))]
        byte[] ExportVetSamplesCount(eidss.model.Reports.Common.BaseYearModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportVetSamplesBySampleType", ReplyAction = "http://tempuri.org/IReportFacade/ExportVetSamplesBySampleTypeResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.KZ.InfectiousParasiticKZSurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.TH.BaseThaiYearModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.TH.NumberOfCasesDeathsMonthTHModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.GG.AnnualInfectiousDiseaseModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.BaseYearQuarterModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.GG.RBESurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.FormNo1SurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.AFPModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.VetLabSurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.ZoonoticSurrogateModel))]
        byte[] ExportVetSamplesBySampleType(eidss.model.Reports.Common.BaseYearModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportVetSamplesBySampleTypesWithinRegions", ReplyAction = "http://tempuri.org/IReportFacade/ExportVetSamplesBySampleTypesWithinRegionsRespon" +
            "se")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.KZ.InfectiousParasiticKZSurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.TH.BaseThaiYearModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.TH.NumberOfCasesDeathsMonthTHModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.GG.AnnualInfectiousDiseaseModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.BaseYearQuarterModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.GG.RBESurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.FormNo1SurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.AFPModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.VetLabSurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.ZoonoticSurrogateModel))]
        byte[] ExportVetSamplesBySampleTypesWithinRegions(eidss.model.Reports.Common.BaseYearModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportVetYearlySituation", ReplyAction = "http://tempuri.org/IReportFacade/ExportVetYearlySituationResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.KZ.InfectiousParasiticKZSurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.TH.BaseThaiYearModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.TH.NumberOfCasesDeathsMonthTHModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.GG.AnnualInfectiousDiseaseModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.BaseYearQuarterModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.GG.RBESurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.FormNo1SurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.AFPModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.VetLabSurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.ZoonoticSurrogateModel))]
        byte[] ExportVetYearlySituation(eidss.model.Reports.Common.BaseYearModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportVetActiveSurveillance", ReplyAction = "http://tempuri.org/IReportFacade/ExportVetActiveSurveillanceResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.KZ.InfectiousParasiticKZSurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.TH.BaseThaiYearModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.TH.NumberOfCasesDeathsMonthTHModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.GG.AnnualInfectiousDiseaseModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.BaseYearQuarterModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.GG.RBESurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.FormNo1SurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.AFPModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.VetLabSurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.ZoonoticSurrogateModel))]
        byte[] ExportVetActiveSurveillance(eidss.model.Reports.Common.BaseYearModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportInfectiousParasiticKZReport", ReplyAction = "http://tempuri.org/IReportFacade/ExportInfectiousParasiticKZReportResponse")]
        byte[] ExportInfectiousParasiticKZReport(eidss.model.Reports.KZ.InfectiousParasiticKZSurrogateModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportVetCountryPreventiveMeasures", ReplyAction = "http://tempuri.org/IReportFacade/ExportVetCountryPreventiveMeasuresResponse")]
        byte[] ExportVetCountryPreventiveMeasures(eidss.model.Reports.KZ.ProphylacticModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportVetCountrySanitaryMeasures", ReplyAction = "http://tempuri.org/IReportFacade/ExportVetCountrySanitaryMeasuresResponse")]
        byte[] ExportVetCountrySanitaryMeasures(eidss.model.Reports.KZ.SanitaryModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportVetCountryPlannedDiagnosticTests", ReplyAction = "http://tempuri.org/IReportFacade/ExportVetCountryPlannedDiagnosticTestsResponse")]
        byte[] ExportVetCountryPlannedDiagnosticTests(eidss.model.Reports.KZ.DiagnosticInvestigationModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportVetOblastPreventiveMeasures", ReplyAction = "http://tempuri.org/IReportFacade/ExportVetOblastPreventiveMeasuresResponse")]
        byte[] ExportVetOblastPreventiveMeasures(eidss.model.Reports.KZ.ProphylacticModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportVetOblastSanitaryMeasures", ReplyAction = "http://tempuri.org/IReportFacade/ExportVetOblastSanitaryMeasuresResponse")]
        byte[] ExportVetOblastSanitaryMeasures(eidss.model.Reports.KZ.SanitaryModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportVetOblastPlannedDiagnosticTests", ReplyAction = "http://tempuri.org/IReportFacade/ExportVetOblastPlannedDiagnosticTestsResponse")]
        byte[] ExportVetOblastPlannedDiagnosticTests(eidss.model.Reports.KZ.DiagnosticInvestigationModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportLimTestResult", ReplyAction = "http://tempuri.org/IReportFacade/ExportLimTestResultResponse")]
        byte[] ExportLimTestResult(eidss.model.Reports.Common.LimTestResultModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportLimSampleTransfer", ReplyAction = "http://tempuri.org/IReportFacade/ExportLimSampleTransferResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.HumIdModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.AggregateActionsModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.VetIdModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimTestResultModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimTestModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimBatchTestModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.AggregateModel))]
        byte[] ExportLimSampleTransfer(eidss.model.Reports.Common.BaseIdModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportLimTest", ReplyAction = "http://tempuri.org/IReportFacade/ExportLimTestResponse")]
        byte[] ExportLimTest(eidss.model.Reports.Common.LimTestModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportLimBatchTest", ReplyAction = "http://tempuri.org/IReportFacade/ExportLimBatchTestResponse")]
        byte[] ExportLimBatchTest(eidss.model.Reports.Common.LimBatchTestModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportLimSample", ReplyAction = "http://tempuri.org/IReportFacade/ExportLimSampleResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.HumIdModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.AggregateActionsModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.VetIdModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimTestResultModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimTestModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimBatchTestModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.AggregateModel))]
        byte[] ExportLimSample(eidss.model.Reports.Common.BaseIdModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportLimContainerContent", ReplyAction = "http://tempuri.org/IReportFacade/ExportLimContainerContentResponse")]
        byte[] ExportLimContainerContent(eidss.model.Reports.Common.LimContainerContentModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportLimAccessionIn", ReplyAction = "http://tempuri.org/IReportFacade/ExportLimAccessionInResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.HumIdModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.AggregateActionsModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.VetIdModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimTestResultModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimTestModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimBatchTestModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.AggregateModel))]
        byte[] ExportLimAccessionIn(eidss.model.Reports.Common.BaseIdModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportLimSampleDestruction", ReplyAction = "http://tempuri.org/IReportFacade/ExportLimSampleDestructionResponse")]
        byte[] ExportLimSampleDestruction(eidss.model.Reports.Common.IdListModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportOutbreak", ReplyAction = "http://tempuri.org/IReportFacade/ExportOutbreakResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.HumIdModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.AggregateActionsModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.VetIdModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimTestResultModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimTestModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimBatchTestModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.AggregateModel))]
        byte[] ExportOutbreak(eidss.model.Reports.Common.BaseIdModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportAdmEventLog", ReplyAction = "http://tempuri.org/IReportFacade/ExportAdmEventLogResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.IQ.SituationOnInfectiousDiseasesSurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.KZ.ProphylacticModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.KZ.SanitaryModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.KZ.DiagnosticInvestigationModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.TH.NumberOfCasesDeathsMorbidityMortalityTHModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.GG.Hum60BJournalModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.GG.IntermediateInfectiousDiseaseSurrogateModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.SummaryByRayonDiagnosisModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.AZ.VetSummaryModel))]
        byte[] ExportAdmEventLog(eidss.model.Reports.Common.BaseIntervalModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportVectorSurveillanceSessionSummary", ReplyAction = "http://tempuri.org/IReportFacade/ExportVectorSurveillanceSessionSummaryResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.HumIdModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.AggregateActionsModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.VetIdModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimTestResultModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimTestModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.LimBatchTestModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eidss.model.Reports.Common.AggregateModel))]
        byte[] ExportVectorSurveillanceSessionSummary(eidss.model.Reports.Common.BaseIdModel model);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportNewBarcodes", ReplyAction = "http://tempuri.org/IReportFacade/ExportNewBarcodesResponse")]
        byte[] ExportNewBarcodes(long barcodeType, int quantity);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportExistingBarcodes", ReplyAction = "http://tempuri.org/IReportFacade/ExportExistingBarcodesResponse")]
        byte[] ExportExistingBarcodes(long barcodeType, long[] idList);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/ExportSampleBarcodes", ReplyAction = "http://tempuri.org/IReportFacade/ExportSampleBarcodesResponse")]
        byte[] ExportSampleBarcodes(bv.common.Core.SampleBarcodeDTO[] samples);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IReportFacade/GetServiceVersion", ReplyAction = "http://tempuri.org/IReportFacade/GetServiceVersionResponse")]
        System.Version GetServiceVersion();
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportFacadeChannel : eidss.mobileclient.MobileReportService.IReportFacade, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportFacadeClient : System.ServiceModel.ClientBase<eidss.mobileclient.MobileReportService.IReportFacade>, eidss.mobileclient.MobileReportService.IReportFacade
    {

        public ReportFacadeClient()
        {
        }

        public ReportFacadeClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public ReportFacadeClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public ReportFacadeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public ReportFacadeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public byte[] ExportHumAggregateCase(eidss.model.Reports.Common.AggregateModel model)
        {
            return base.Channel.ExportHumAggregateCase(model);
        }

        public byte[] ExportHumAggregateCaseSummary(eidss.model.Reports.Common.AggregateSummaryModel model)
        {
            return base.Channel.ExportHumAggregateCaseSummary(model);
        }

        public byte[] ExportHumCaseInvestigation(eidss.model.Reports.Common.HumIdModel model)
        {
            return base.Channel.ExportHumCaseInvestigation(model);
        }

        public byte[] ExportHumUrgentyNotification(eidss.model.Reports.Common.BaseIdModel model)
        {
            return base.Channel.ExportHumUrgentyNotification(model);
        }

        public byte[] ExportHumDiagnosisToChangedDiagnosis(eidss.model.Reports.Common.DToChangedDSurrogateModel model)
        {
            return base.Channel.ExportHumDiagnosisToChangedDiagnosis(model);
        }

        public byte[] ExportHumMonthlyMorbidityAndMortality(eidss.model.Reports.Common.BaseDateModel model)
        {
            return base.Channel.ExportHumMonthlyMorbidityAndMortality(model);
        }

        public byte[] ExportHum60BJournal(eidss.model.Reports.GG.Hum60BJournalModel model)
        {
            return base.Channel.ExportHum60BJournal(model);
        }

        public byte[] ExportHumMonthInfectiousDiseaseV4(eidss.model.Reports.GG.MonthInfectiousDiseaseModel model)
        {
            return base.Channel.ExportHumMonthInfectiousDiseaseV4(model);
        }

        public byte[] ExportHumMonthInfectiousDiseaseV5(eidss.model.Reports.GG.MonthInfectiousDiseaseModel model)
        {
            return base.Channel.ExportHumMonthInfectiousDiseaseV5(model);
        }

        public byte[] ExportHumMonthInfectiousDiseaseV6(eidss.model.Reports.GG.MonthInfectiousDiseaseModel model)
        {
            return base.Channel.ExportHumMonthInfectiousDiseaseV6(model);
        }

        public byte[] ExportHumMonthInfectiousDiseaseV61(eidss.model.Reports.GG.MonthInfectiousDiseaseModel model)
        {
            return base.Channel.ExportHumMonthInfectiousDiseaseV61(model);
        }

        public byte[] ExportHumIntermediateMonthInfectiousDiseaseV4(eidss.model.Reports.GG.IntermediateInfectiousDiseaseSurrogateModel model)
        {
            return base.Channel.ExportHumIntermediateMonthInfectiousDiseaseV4(model);
        }

        public byte[] ExportHumIntermediateMonthInfectiousDiseaseV5(eidss.model.Reports.GG.IntermediateInfectiousDiseaseSurrogateModel model)
        {
            return base.Channel.ExportHumIntermediateMonthInfectiousDiseaseV5(model);
        }

        public byte[] ExportHumIntermediateMonthInfectiousDiseaseV6(eidss.model.Reports.GG.IntermediateInfectiousDiseaseSurrogateModel model)
        {
            return base.Channel.ExportHumIntermediateMonthInfectiousDiseaseV6(model);
        }

        public byte[] ExportHumIntermediateMonthInfectiousDiseaseV61(eidss.model.Reports.GG.IntermediateInfectiousDiseaseSurrogateModel model)
        {
            return base.Channel.ExportHumIntermediateMonthInfectiousDiseaseV61(model);
        }

        public byte[] ExportHumAnnualInfectiousDisease(eidss.model.Reports.GG.AnnualInfectiousDiseaseModel model)
        {
            return base.Channel.ExportHumAnnualInfectiousDisease(model);
        }

        public byte[] ExportHumIntermediateAnnualInfectiousDisease(eidss.model.Reports.GG.IntermediateInfectiousDiseaseSurrogateModel model)
        {
            return base.Channel.ExportHumIntermediateAnnualInfectiousDisease(model);
        }

        public byte[] ExportHumSerologyResearchCard(eidss.model.Reports.GG.HumanLabSampleModel model)
        {
            return base.Channel.ExportHumSerologyResearchCard(model);
        }

        public byte[] ExportHumMicrobiologyResearchCard(eidss.model.Reports.GG.HumanLabSampleModel model)
        {
            return base.Channel.ExportHumMicrobiologyResearchCard(model);
        }

        public byte[] ExportHumAntibioticResistanceCard(eidss.model.Reports.GG.HumanLabSampleModel model)
        {
            return base.Channel.ExportHumAntibioticResistanceCard(model);
        }

        public byte[] ExportHumAntibioticResistanceCardLma(eidss.model.Reports.Common.VetLabSampleModel model)
        {
            return base.Channel.ExportHumAntibioticResistanceCardLma(model);
        }

        public byte[] ExportVetRabiesBulletinEurope(eidss.model.Reports.GG.RBESurrogateModel model)
        {
            return base.Channel.ExportVetRabiesBulletinEurope(model);
        }

        public byte[] ExportVetLaboratoryResearchResult(eidss.model.Reports.GG.VetLaboratoryResearchResultModel model)
        {
            return base.Channel.ExportVetLaboratoryResearchResult(model);
        }

        public byte[] ExportHumFormN1(eidss.model.Reports.AZ.FormNo1SurrogateModel model)
        {
            return base.Channel.ExportHumFormN1(model);
        }

        public byte[] ExportHumDataQualityIndicators(eidss.model.Reports.AZ.DataQualityIndicatorsSurrogateModel surrogateModel)
        {
            return base.Channel.ExportHumDataQualityIndicators(surrogateModel);
        }

        public byte[] ExportHumDataQualityIndicatorsRayons(eidss.model.Reports.AZ.DataQualityIndicatorsSurrogateModel surrogateModel)
        {
            return base.Channel.ExportHumDataQualityIndicatorsRayons(surrogateModel);
        }

        public byte[] ExportHumSummaryByRayonDiagnosisAgeGroups(eidss.model.Reports.AZ.SummaryByRayonDiagnosisModel model)
        {
            return base.Channel.ExportHumSummaryByRayonDiagnosisAgeGroups(model);
        }

        public byte[] ExportHumComparativeAZReport(eidss.model.Reports.AZ.ComparativeSurrogateModel model)
        {
            return base.Channel.ExportHumComparativeAZReport(model);
        }

        public byte[] ExportHumExternalComparativeReport(eidss.model.Reports.AZ.ExternalComparativeSurrogateModel model)
        {
            return base.Channel.ExportHumExternalComparativeReport(model);
        }

        public byte[] ExportHumMainIndicatorsOfAFPSurveillance(eidss.model.Reports.AZ.AFPModel model)
        {
            return base.Channel.ExportHumMainIndicatorsOfAFPSurveillance(model);
        }

        public byte[] ExportHumAdditionalIndicatorsOfAFPSurveillance(eidss.model.Reports.AZ.AFPModel model)
        {
            return base.Channel.ExportHumAdditionalIndicatorsOfAFPSurveillance(model);
        }

        public byte[] ExportHumWhoMeaslesRubellaReport(eidss.model.Reports.AZ.WhoMeaslesRubellaModel model)
        {
            return base.Channel.ExportHumWhoMeaslesRubellaReport(model);
        }

        public byte[] ExportHumComparativeReportOfTwoYears(eidss.model.Reports.AZ.ComparativeTwoYearsSurrogateModel model)
        {
            return base.Channel.ExportHumComparativeReportOfTwoYears(model);
        }

        public byte[] ExportHumBorderRayonsComparativeReport(eidss.model.Reports.AZ.BorderRayonsSurrogateModel model)
        {
            return base.Channel.ExportHumBorderRayonsComparativeReport(model);
        }

        public byte[] ExportHumTuberculosisCasesTested(eidss.model.Reports.AZ.TuberculosisSurrogateModel model)
        {
            return base.Channel.ExportHumTuberculosisCasesTested(model);
        }

        public byte[] ExportLabTestingResultsAZ(eidss.model.Reports.AZ.LabTestingTesultsModel model)
        {
            return base.Channel.ExportLabTestingResultsAZ(model);
        }

        public byte[] ExportAssignmentLabDiagnosticAZ(eidss.model.Reports.AZ.AssignmentLabDiagnosticModel model)
        {
            return base.Channel.ExportAssignmentLabDiagnosticAZ(model);
        }

        public byte[] ExportZoonoticComparativeAZ(eidss.model.Reports.AZ.ZoonoticSurrogateModel model)
        {
            return base.Channel.ExportZoonoticComparativeAZ(model);
        }

        public byte[] ExportHumComparativeIQReport(eidss.model.Reports.AZ.ComparativeSurrogateModel model)
        {
            return base.Channel.ExportHumComparativeIQReport(model);
        }

        public byte[] ExportWeeklySituationDiseasesByAgeGroupAndSex(eidss.model.Reports.IQ.SituationOnInfectiousDiseasesSurrogateModel model)
        {
            return base.Channel.ExportWeeklySituationDiseasesByAgeGroupAndSex(model);
        }

        public byte[] ExportMonthlySituationDiseasesByAgeGroupAndSex(eidss.model.Reports.IQ.SituationOnInfectiousDiseasesSurrogateModel model)
        {
            return base.Channel.ExportMonthlySituationDiseasesByAgeGroupAndSex(model);
        }

        public byte[] ExportWeeklySituationDiseasesByDistricts(eidss.model.Reports.IQ.SituationOnInfectiousDiseasesSurrogateModel model)
        {
            return base.Channel.ExportWeeklySituationDiseasesByDistricts(model);
        }

        public byte[] ExportMonthlySituationDiseasesByDistricts(eidss.model.Reports.IQ.SituationOnInfectiousDiseasesSurrogateModel model)
        {
            return base.Channel.ExportMonthlySituationDiseasesByDistricts(model);
        }

        public byte[] ExportVeterinaryCasesReport(eidss.model.Reports.AZ.VetCasesSurrogateModel model)
        {
            return base.Channel.ExportVeterinaryCasesReport(model);
        }

        public byte[] ExportVeterinaryLaboratoriesAZReport(eidss.model.Reports.AZ.VetLabSurrogateModel model)
        {
            return base.Channel.ExportVeterinaryLaboratoriesAZReport(model);
        }

        public byte[] ExportVeterinaryFormVet1(eidss.model.Reports.AZ.VetCasesSurrogateModel model)
        {
            return base.Channel.ExportVeterinaryFormVet1(model);
        }

        public byte[] ExportVeterinaryFormVet1A(eidss.model.Reports.AZ.VetCasesSurrogateModel model)
        {
            return base.Channel.ExportVeterinaryFormVet1A(model);
        }

        public byte[] ExportVeterinarySummaryAZ(eidss.model.Reports.AZ.VetSummaryModel model)
        {
            return base.Channel.ExportVeterinarySummaryAZ(model);
        }

        public byte[] ExportHumComparativeReportOfSeveralYearsTH(eidss.model.Reports.TH.ComparativeSeveralYearsTHSurrogateModel model)
        {
            return base.Channel.ExportHumComparativeReportOfSeveralYearsTH(model);
        }

        public byte[] ExportHumNumberOfCasesDeathsMorbidityMortalityTH(eidss.model.Reports.TH.NumberOfCasesDeathsMorbidityMortalityTHModel model)
        {
            return base.Channel.ExportHumNumberOfCasesDeathsMorbidityMortalityTH(model);
        }

        public byte[] ExportHumNumberOfCasesDeathsMonthTH(eidss.model.Reports.TH.NumberOfCasesDeathsMonthTHModel model)
        {
            return base.Channel.ExportHumNumberOfCasesDeathsMonthTH(model);
        }

        public byte[] ExportHumFormN85ARM(eidss.model.Reports.ARM.FormN85SurrogateModel model)
        {
            return base.Channel.ExportHumFormN85ARM(model);
        }

        public byte[] ExportVetAggregateCase(eidss.model.Reports.Common.AggregateModel model)
        {
            return base.Channel.ExportVetAggregateCase(model);
        }

        public byte[] ExportVetAggregateCaseSummary(eidss.model.Reports.Common.AggregateSummaryModel model)
        {
            return base.Channel.ExportVetAggregateCaseSummary(model);
        }

        public byte[] ExportVetAggregateCaseActions(eidss.model.Reports.Common.AggregateActionsModel model)
        {
            return base.Channel.ExportVetAggregateCaseActions(model);
        }

        public byte[] ExportVetAggregateCaseActionsSummary(eidss.model.Reports.Common.AggregateActionsSummaryModel model)
        {
            return base.Channel.ExportVetAggregateCaseActionsSummary(model);
        }

        public byte[] ExportVetAvianInvestigation(eidss.model.Reports.Common.VetIdModel model)
        {
            return base.Channel.ExportVetAvianInvestigation(model);
        }

        public byte[] ExportVetLivestockInvestigation(eidss.model.Reports.Common.VetIdModel model)
        {
            return base.Channel.ExportVetLivestockInvestigation(model);
        }

        public byte[] ExportVetActiveSurveillanceSampleCollected(eidss.model.Reports.Common.BaseIdModel model)
        {
            return base.Channel.ExportVetActiveSurveillanceSampleCollected(model);
        }

        public byte[] ExportVetSamplesCount(eidss.model.Reports.Common.BaseYearModel model)
        {
            return base.Channel.ExportVetSamplesCount(model);
        }

        public byte[] ExportVetSamplesBySampleType(eidss.model.Reports.Common.BaseYearModel model)
        {
            return base.Channel.ExportVetSamplesBySampleType(model);
        }

        public byte[] ExportVetSamplesBySampleTypesWithinRegions(eidss.model.Reports.Common.BaseYearModel model)
        {
            return base.Channel.ExportVetSamplesBySampleTypesWithinRegions(model);
        }

        public byte[] ExportVetYearlySituation(eidss.model.Reports.Common.BaseYearModel model)
        {
            return base.Channel.ExportVetYearlySituation(model);
        }

        public byte[] ExportVetActiveSurveillance(eidss.model.Reports.Common.BaseYearModel model)
        {
            return base.Channel.ExportVetActiveSurveillance(model);
        }

        public byte[] ExportInfectiousParasiticKZReport(eidss.model.Reports.KZ.InfectiousParasiticKZSurrogateModel model)
        {
            return base.Channel.ExportInfectiousParasiticKZReport(model);
        }

        public byte[] ExportVetCountryPreventiveMeasures(eidss.model.Reports.KZ.ProphylacticModel model)
        {
            return base.Channel.ExportVetCountryPreventiveMeasures(model);
        }

        public byte[] ExportVetCountrySanitaryMeasures(eidss.model.Reports.KZ.SanitaryModel model)
        {
            return base.Channel.ExportVetCountrySanitaryMeasures(model);
        }

        public byte[] ExportVetCountryPlannedDiagnosticTests(eidss.model.Reports.KZ.DiagnosticInvestigationModel model)
        {
            return base.Channel.ExportVetCountryPlannedDiagnosticTests(model);
        }

        public byte[] ExportVetOblastPreventiveMeasures(eidss.model.Reports.KZ.ProphylacticModel model)
        {
            return base.Channel.ExportVetOblastPreventiveMeasures(model);
        }

        public byte[] ExportVetOblastSanitaryMeasures(eidss.model.Reports.KZ.SanitaryModel model)
        {
            return base.Channel.ExportVetOblastSanitaryMeasures(model);
        }

        public byte[] ExportVetOblastPlannedDiagnosticTests(eidss.model.Reports.KZ.DiagnosticInvestigationModel model)
        {
            return base.Channel.ExportVetOblastPlannedDiagnosticTests(model);
        }

        public byte[] ExportLimTestResult(eidss.model.Reports.Common.LimTestResultModel model)
        {
            return base.Channel.ExportLimTestResult(model);
        }

        public byte[] ExportLimSampleTransfer(eidss.model.Reports.Common.BaseIdModel model)
        {
            return base.Channel.ExportLimSampleTransfer(model);
        }

        public byte[] ExportLimTest(eidss.model.Reports.Common.LimTestModel model)
        {
            return base.Channel.ExportLimTest(model);
        }

        public byte[] ExportLimBatchTest(eidss.model.Reports.Common.LimBatchTestModel model)
        {
            return base.Channel.ExportLimBatchTest(model);
        }

        public byte[] ExportLimSample(eidss.model.Reports.Common.BaseIdModel model)
        {
            return base.Channel.ExportLimSample(model);
        }

        public byte[] ExportLimContainerContent(eidss.model.Reports.Common.LimContainerContentModel model)
        {
            return base.Channel.ExportLimContainerContent(model);
        }

        public byte[] ExportLimAccessionIn(eidss.model.Reports.Common.BaseIdModel model)
        {
            return base.Channel.ExportLimAccessionIn(model);
        }

        public byte[] ExportLimSampleDestruction(eidss.model.Reports.Common.IdListModel model)
        {
            return base.Channel.ExportLimSampleDestruction(model);
        }

        public byte[] ExportOutbreak(eidss.model.Reports.Common.BaseIdModel model)
        {
            return base.Channel.ExportOutbreak(model);
        }

        public byte[] ExportAdmEventLog(eidss.model.Reports.Common.BaseIntervalModel model)
        {
            return base.Channel.ExportAdmEventLog(model);
        }

        public byte[] ExportVectorSurveillanceSessionSummary(eidss.model.Reports.Common.BaseIdModel model)
        {
            return base.Channel.ExportVectorSurveillanceSessionSummary(model);
        }

        public byte[] ExportNewBarcodes(long barcodeType, int quantity)
        {
            return base.Channel.ExportNewBarcodes(barcodeType, quantity);
        }

        public byte[] ExportExistingBarcodes(long barcodeType, long[] idList)
        {
            return base.Channel.ExportExistingBarcodes(barcodeType, idList);
        }

        public byte[] ExportSampleBarcodes(bv.common.Core.SampleBarcodeDTO[] samples)
        {
            return base.Channel.ExportSampleBarcodes(samples);
        }

        public System.Version GetServiceVersion()
        {
            return base.Channel.GetServiceVersion();
        }
    }
}
