using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace eidss.model.Enums
{
    public enum MenuIconsSmall
    {
        ASCampaignJournal = 0,
        ASSessionJournal = 1,
        AliquotsDerivatives = 2,
        AvianCase = 3,
        Batch = 4,
        BatchJournal = 5,
        Farm = 6,
        Freezer = 7,
        Help = 8,
        HumanAggregateCase = 9,
        HumanCase = 10,
        HumanCaseDeduplication = 11,
        LivestockCase = 12,
        Outbreak = 13,
        OutbreakJournal = 14,
        SampleAccession = 15,
        SampleDisposition = 16,
        SampleDispositionJournal = 17,
        SampleJournal = 18,
        SampleTransferIn = 19,
        SampleTransferJournal = 20,
        SampleTransferOut = 21,
        SearchHumanCase = 22,
        SearchHumanCaseInBrowseMode = 23,
        SearchHumanCasesForDeduplication = 24,
        SearchVetCase = 25,
        SelectTests = 26,
        TestJournal = 27,
        VetAggregateAction = 28,
        VetAggregateCase = 29,
        HumanAggregateCaseSummary = 30,
        VetAggregateActionSummary = 31,
        VetAggregateCaseSummary = 32,
        English = 33,
        Armenian = 34,
        Azery = 35,
        Georgian = 36,
        Kazakhstan = 37,
        Russian = 38,
        Ukrainian = 39,
        ASCampaign = 40,
        ASSession = 41,
        OrganizationsList = 42,
        Administration = 43,
        UniqueNumberingScheme = 44,
        AggregateSettings = 45,
        EmployeesList = 46,
        FFDesigner = 47,
        MapCustomization = 48,
        ParameterTypesEditor = 49,
        Permissions = 50,
        SettlementsList = 51,
        StatisticalDataList = 52,
        Configuration = 53,
        AggregateMatrix = 54,
        ChangePassword = 55,
        DataAccessTypes = 56,
        DataAuditTransactions = 57,
        EidssSites = 58,
        EventLog = 59,
        Exit = 60,
        LabSampleLogBook = 61,
        LaunchAVR = 62,
        Options = 63,
        References = 64,
        ReferenceMatrix = 65,
        SecurityPolicy = 66,
        SecurityEventLog = 67,
        SiteAlertSubscriptions = 66,
        SwitchUser = 69,
        SystemFunctions = 70,
        UserGroupList = 71,
        VsSessionDetail = 72,
        VsSessionList = 73,
        HumanAggregateCaseList = 74,
        VetAggregateActionList = 75,
        VetAggregateCaseList = 76,
        PrintBarcode = 77,
        DataArchiveSettings = 78,
        PersonsJournal = 79,
        Iraq = 80,
        Reports = 81,
        PDF = 82,
        Bss = 83,
        BssList =84,
        BssAggregate = 85,
        BssAggregateList = 86,
        BssAberrationReport = 87,
        AdminReport = 88,
        HumanAberrationReport = 89,
        HumanReport = 90,
        LabReport = 91,
        VetReport = 92,
        EpiInfo=93,
        HumanAggregateDeduplication=94,
        VetAggregateActionDeduplication=95,
        VetAggregateDeduplication = 96,
        VetAberrationReport = 97,
        ReplicateData = 98,
        AberrationReport = 99,
        Thailand = 100,
    }
}
