pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./administrative_support.htm","ՀՀԷՀՀ կարգավորումներ &#62; Ադմինիստրատիվ գործիքներ","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./age_groups-statistical_age_groups_matrix.htm","ՀՀԷՀՀ կարգավորումներ &#62; Տարիքային խմբեր - Վիճակագրական տարիքային խմբեր մատրիցա","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./age_groups_editor.htm","ՀՀԷՀՀ կարգավորումներ &#62; Տարիքային խմբերի խմբագրիչ","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./aggregatesettings.htm","ՀՀԷՀՀ կարգավորումներ &#62; Ցուցակային հաշվետվությունների կարգավորումներ","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./basic_reference_editor.htm","ՀՀԷՀՀ կարգավորումներ &#62; Տեղեկատուների խմբագրիչ","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./case_classification_editor.htm","ՀՀԷՀՀ կարգավորումներ &#62; Դեպքի դասակարգման խմբագրիչ","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./clinical_diagnosis_editor.htm","ՀՀԷՀՀ կարգավորումներ &#62; Կլինիկական ախտորոշումների խմբագրիչ","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./custom_report_rows.htm","ՀՀԷՀՀ կարգավորումներ &#62; Օգտվողի հաշվետվության տողեր","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./data_archiving_settings.htm","ՀՀԷՀՀ կարգավորումներ &#62; Տվյալների արխիվացման կարգավորումեր","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./data_audit_management.htm","ՀՀԷՀՀ կարգավորումներ &#62; Ադմինիստրատիվ գործիքներ &#62; Տվյալների աուդիտի գործարքներ","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./diagnoses-age_groups_matrix.htm","ՀՀԷՀՀ կարգավորումներ &#62; Ախտորոշում - տարիքային խմբեր մատրիցա","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./diagnoses_group-diagnosis_matrix.htm","ՀՀԷՀՀ կարգավորումներ &#62; Ախտորոշումների խումբ -Ախտորոշումներ մատրիցա","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./diagnosis-lab_tests_matrix.htm","ՀՀԷՀՀ կարգավորումներ &#62; Ախտորոշում-լաբորատոր հետազոտություն մատրիցա","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./diagnosis-penside_tests_matrix.htm","ՀՀԷՀՀ կարգավորումներ &#62; Ախտորոշում-էքսպրես հետազոտություններ մատրիցա","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./diagnosis-sample_types_matrix.htm","ՀՀԷՀՀ կարգավորումներ &#62; Ախտորոշում-նմուշի տեսակներ մատրիցա","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./eidss_configuration.htm","ՀՀԷՀՀ կարգավորումներ","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./eidss_sites.htm","ՀՀԷՀՀ կարգավորումներ &#62; Անվտանգության կոնֆիգուրացիաներ &#62; ՀՀԷՀՀ կայքեր","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./employees_users.htm","ՀՀԷՀՀ կարգավորումներ &#62; Ադմինիստրացիայի կարգավորումներ &#62; Աշխատակիցներ/ Օգտագործողներ","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./farms.htm","ՀՀԷՀՀ կարգավորումներ &#62; Ադմինիստրացիայի կարգավորումներ &#62; Տնտեսություններ","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./ffd_-_to_delete_a_template.htm","ՀՀԷՀՀ կարգավորումներ &#62; Ճկուն ձևերի խմբագրիչ &#62; ՃՁՁ - Ջնջել ձևանմուշը","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./ffd_fields_and_sections.htm","ՀՀԷՀՀ կարգավորումներ &#62; Ճկուն ձևերի խմբագրիչ &#62; ՃՁՁ - Ձևանմուշի բաժիններ և դաշտեր","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./ffd_to_add_template.htm","ՀՀԷՀՀ կարգավորումներ &#62; Ճկուն ձևերի խմբագրիչ &#62; ՃՁՁ - Ավելացնել նոր ձևանմուշ","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./ffd_to_edit_template.htm","ՀՀԷՀՀ կարգավորումներ &#62; Ճկուն ձևերի խմբագրիչ &#62; ՃՁՁ - Խմբագրել ձևանմուշը","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./form_design.htm","ՀՀԷՀՀ կարգավորումներ &#62; Ճկուն ձևերի խմբագրիչ","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./human_aggregate_case_matrix_ed.htm","ՀՀԷՀՀ կարգավորումներ &#62; Մարդու ցուցակային դեպքի մատրիցա","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./maps_configuration.htm","ՀՀԷՀՀ կարգավորումներ &#62; Քարտեզի կարգավորումներ","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./measure_reference_editor.htm","ՀՀԷՀՀ կարգավորումներ &#62; Միջոցառումների տեղեկատուի խմբագրիչ","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./organisations.htm","ՀՀԷՀՀ կարգավորումներ &#62; Ադմինիստրացիայի կարգավորումներ &#62; Կազմակերպություններ","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./parameter_types_matrix.htm","ՀՀԷՀՀ կարգավորումներ &#62; Պարամետրերի տեսակների խմբագրիչ","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./persons_list.htm","ՀՀԷՀՀ կարգավորումներ &#62; Ադմինիստրացիայի կարգավորումներ &#62; Համակարգում գրանցված մարդկանց ցանկ","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./report_diagnoses_group-diagnosis_matrix.htm","ՀՀԷՀՀ կարգավորումներ &#62; Հաշվետվությունների ախտորոշումների խումբ-ախտորոշում մատրիցա","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./report_diagnoses_groups_editor.htm","ՀՀԷՀՀ կարգավորումներ &#62; Հաշվետվությունների ախտորոշումների խմբերի  խմբագրիչ","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./repository_schema.htm","ՀՀԷՀՀ կարգավորումներ &#62; Պահեստի սխեմա","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./sample_type-derivative_type_ma.htm","ՀՀԷՀՀ կարգավորումներ &#62; Նմուշի տեսակ-նմուշի ածանցյալի մատրիցա","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./sample_type_reference_editor.htm","ՀՀԷՀՀ կարգավորումներ &#62; Նմուշների տեսակի խմբագրիչ","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./security.htm","ՀՀԷՀՀ կարգավորումներ &#62; Անվտանգության կոնֆիգուրացիաներ &#62; Մուտքի իրավունքի կառավարում","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./security_log.htm","ՀՀԷՀՀ կարգավորումներ &#62; Ադմինիստրատիվ գործիքներ &#62; Անվտանգության իրադարձությունների գրանցամատյան","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./security_policy.htm","ՀՀԷՀՀ կարգավորումներ &#62; Անվտանգության կոնֆիգուրացիաներ &#62; Անվտանգության քաղաքականություն","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./settlements.htm","ՀՀԷՀՀ կարգավորումներ &#62; Ադմինիստրացիայի կարգավորումներ &#62; Բնակավայրեր","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./species-animal_age_matrix.htm","ՀՀԷՀՀ կարգավորումներ &#62; Կենդանատեսակներ-կենդանու տարիք մատրիցա","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./species_type_reference_editor.htm","ՀՀԷՀՀ կարգավորումներ &#62; Կենդանատեսակների խմբագրիչ","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./statistics.htm","ՀՀԷՀՀ կարգավորումներ &#62; Ադմինիստրացիայի կարգավորումներ &#62; Վիճակագրություն","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./statistic_types_editor.htm","ՀՀԷՀՀ կարգավորումներ &#62; Վիճակագրական հաշվետվությունների տեսակների խմբագրիչ","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./system_event_log.htm","ՀՀԷՀՀ կարգավորումներ &#62; Ադմինիստրատիվ գործիքներ &#62; Իրադարձություններ մատյան","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./system_functions_list.htm","ՀՀԷՀՀ կարգավորումներ &#62; Անվտանգության կոնֆիգուրացիաներ &#62; Մուտքի իրավունքի կառավարումի ցանկ","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./test_results_matrix.htm","ՀՀԷՀՀ կարգավորումներ &#62; Հետազոտություն-հետազոտության արդյունք մատրիցա","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./unique_numbering_schema.htm","ՀՀԷՀՀ կարգավորումներ &#62; Առանձնահատուկ համարակալման սխեմայի ցանկ","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./user_groups.htm","ՀՀԷՀՀ կարգավորումներ &#62; Անվտանգության կոնֆիգուրացիաներ &#62;  Օգտագործողների խմբեր","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./vector_species_types.htm","ՀՀԷՀՀ կարգավորումներ &#62; Պահոցների/փոխանցողների կենդանատեսակների խմբագրիչ","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./vector_type-collection_method_matrix.htm","ՀՀԷՀՀ կարգավորումներ &#62; Պահոցների/փոխանցողների տեսակ-հավաքագրման մեթոդների մատրիցա","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./vector_type-field_test_matrix.htm","ՀՀԷՀՀ կարգավորումներ &#62; Պահոցների/փոխանցողների տեսակ-Դաշտային հետազոտությունների մատրիցա","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./vector_type-sample_type_matrix.htm","ՀՀԷՀՀ կարգավորումներ &#62; Պահոցների/փոխանցողների տեսակ-&#62;նմուշի տեսակ մատրիցա ","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./vector_types_editor.htm","ՀՀԷՀՀ կարգավորումներ &#62; Պահոցների/փոխանցողների տեսակի խմբագրիչ","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./vet_aggregate_case_matrix_edit.htm","ՀՀԷՀՀ կարգավորումներ &#62; Կենդանու/թռչնի ծանուցման ենթակա հիվանդությունների հաշվետվության մատրիցա","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./vet_diag_invest_matrix_editor.htm","ՀՀԷՀՀ կարգավորումներ &#62; Անասնաբուժական ախտորոշիչ հետազոտությունների մատրիցա","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./vet_prophylactic_measure_matri.htm","ՀՀԷՀՀ կարգավորումներ &#62; Անասնաբուժական կանխարգելման միջոցառումների մատրիցա","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""],
["./vet_sanitary_action_matrix_edi.htm","ՀՀԷՀՀ կարգավորումներ &#62; Անասնաբուժասանիտարական միջոցառումների մատրիցայի խմբագրիչ","TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help &#38; Manual will scramble individual characters in random words in your publish...",""]];
